### ISSUE TITLE
CIRepository files are being ignored

### ISSUE THREAD

**Issue by kbortnik** [Kentico/KenticoGitignore#2]
Certain patterns, such as `*.user`, are erroneously ignoring files in the `CMS/App_Data/CIRepository` folder.

Tested on Kentico v10.0.5.

### Steps to reproduce:
 1. Ensure that the Kentico `.gitignore` is in place, and all changes are committed (clean working directory)
 2. Enable Continuous Integration in Kentico
 3. Serialise all objects through the CI application
 4. `git add --all && git commit -m "Add CI files"`
 5. `git push` the changes
 6. `git pull` the changes on another copy of the same project, and run `ContinuousIntegration.exe -r`

The result is that a bunch of objects in folders that end with `.user`, are deleted.

### Proposed fix
 1. Apply fix from #1
 2. `git add --all && git status`, and the missing files will show up

#### List of affected files
From a test instance with the Dancing Goat template installed:

    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/checkoutregistration_e-commerce.xml
    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/checkoutregistrationmobileecommercesite.xml
    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/dancinggoat-personaldetails.xml
    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/dancinggoat_userregistration.xml
    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/displayprofile.xml
    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/displayprofilecorporatesite.xml
    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/displayprofileintranet.xml
    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/editprofile.xml
    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/editprofilecommunity.xml
    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/editprofileintranet.xml
    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/editprofilemydesk.xml
    CMS/App_Data/CIRepository/@global/cms.alternativeform/cms.systemtable_cms.user/registrationform.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.class_chat.user/insert.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.class_chat.user/selectusersnicknamecount.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.class_chat.user/update.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/addusertorole.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/addusertosite.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/authenticateuser.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/deleteexpiredsession.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/deletesession.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/deletesessionbysite.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/deletesessionsforuser.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/finduserinsite.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/findusersinrole.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/isauthorizedperclass.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/isauthorizedpernode.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/isauthorizedperresource.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/removesessioncontact.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectallofsite.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectallsettingsroles.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectallview.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectbyrole.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectbyusername.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectmembershipuserroles.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectonlineusers.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectroles.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectrolesbymembership.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectusernamebyid.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectusersession.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectusersessioncount.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectusersinrole.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/selectusersites.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/updatesessionbulk.xml
    CMS/App_Data/CIRepository/@global/cms.query/cms.systemtable_cms.user/updateusercounts.xml
    CMS/App_Data/CIRepository/@global/cms.user/administrator.xml
    CMS/App_Data/CIRepository/@global/cms.user/andy.xml
    CMS/App_Data/CIRepository/@global/cms.user/laura.xml
    CMS/App_Data/CIRepository/@global/cms.user/public.xml
    CMS/App_Data/CIRepository/dancinggoat/cms.scheduledtask/content.publish.xml

**Comment by ChristopherJennings** [comment]
@kbortnik, thank you for submitting this issue and the associated PR. I've gone ahead and merged that into master.
